Backend table changes
eduhub-org/eduhub pull request #75
Opened 2021-08-24 15:29 UTC by ckru-cbb

2021-08-25 16:16 UTC, fschindler requested changes
Took me some time to review all this. I've requested some changes (maybe I commit some myself).

The migrations don't run at all and you have to set everything up again. For the future it would be nice if the complete dataset could simply be taken over by the migrations.

2021-08-25 16:16 UTC, fschindler commented on backend/metadata/databases/default/tables/public_Attendance.yaml
> +    foreign_key_constraint_on: UserId
The permissions from the old `Attendence` table are missing.

2021-08-25 16:16 UTC, fschindler commented on backend/metadata/databases/default/tables/tables.yaml
> -- "!include public_SessionReferent.yaml"
There still exists some files in the repo wich doesn't get used here anymore.

2021-08-25 16:16 UTC, fschindler commented on backend/migrations/default/1629362271453_alter_table_public_Enrollment_alter_column_MotivationGrade/up.sql
> +alter table "public"."Enrollment" rename column "MotivationGrade" to "MotivationRating";
The name of the foreign key is still `Enrollment_MotivationGrade_fkey`. This was quite confusing!

2021-08-25 16:16 UTC, fschindler commented on backend/metadata/databases/default/tables/public_Enrollment.yaml
> +    foreign_key_constraint_on: MotivationRating
The default value of the column `MotivationRating` doesn't exists in the enum table `MotivationRating` which will result in the following error while creating a new record in the `Enrollment` table:
```
Error: Foreign key violation. insert or update on table "Enrollment" violates foreign key constraint "Enrollment_MotivationGrade_fkey"
```

2021-08-25 16:16 UTC, fschindler commented on backend/metadata/databases/default/tables/public_Session.yaml
> +        name: AttendanceDocument
The relation's name still is `AttendenceDocuments`. It should be `AttendanceDocuments`.

2021-08-25 16:16 UTC, fschindler commented on backend/metadata/databases/default/tables/public_Session.yaml
>  - name: Attendences
This should be `Attendance`.

2021-08-25 16:18 UTC, fschindler commented on backend/metadata/databases/default/tables/public_Attendance.yaml
> +    foreign_key_constraint_on: UserId
I've reintroduced the permissions.

2021-08-25 16:18 UTC, fschindler commented on backend/metadata/databases/default/tables/tables.yaml
> -- "!include public_SessionReferent.yaml"
I've removed these files.

2021-08-26 09:24 UTC, ckru-kiel commented on backend/migrations/default/1629362271453_alter_table_public_Enrollment_alter_column_MotivationGrade/up.sql
> +alter table "public"."Enrollment" rename column "MotivationGrade" to "MotivationRating";
renamed that. really hate that hasura can't refactor

2021-08-26 09:25 UTC, fschindler commented on backend/metadata/databases/default/tables/public_Session.yaml
> +        name: AttendanceDocument
I've renamed this.

2021-08-26 09:25 UTC, fschindler commented on backend/metadata/databases/default/tables/public_Session.yaml
>  - name: Attendences
I've renamed this.

2021-08-26 09:29 UTC, ckru-kiel commented on backend/metadata/databases/default/tables/public_Enrollment.yaml
> +    foreign_key_constraint_on: MotivationRating
removed the default value. i believe default should be null which can be interpreted as "unrated"

2021-08-26 09:40 UTC, fschindler commented on backend/metadata/databases/default/tables/public_Enrollment.yaml
> +    foreign_key_constraint_on: MotivationRating
I'm not in charge of deciding the business logic, @steffen74 has to provide the default value. But technically it doesn't make sense, because zero is not allowed here:
```
Error: Not-NULL violation. null value in column "MotivationRating" violates not-null constraint
```

2021-08-26 09:55 UTC, steffen74 commented on backend/metadata/databases/default/tables/public_Enrollment.yaml
> +    foreign_key_constraint_on: MotivationRating
The default value should be the ENUM `UNRATED`.

2021-08-26 10:02 UTC, ckru-kiel commented on backend/metadata/databases/default/tables/public_Enrollment.yaml
> +    foreign_key_constraint_on: MotivationRating
added unrated to motivation rating enum and reintruduced default value

2021-08-26 13:02 UTC, fschindler requested changes

2021-08-26 13:02 UTC, fschindler commented on backend/migrations/default/1629358768576_alter_table_public_Program_add_column_VisiblityParticipationCertificate/up.sql
> +alter table "public"."Program" add column "VisiblityParticipationCertificate" boolean
Found another Typo here: should be `VisibilityParticipationCertificate` instead of `VisiblityParticipationCertificate`.

2021-08-26 13:30 UTC, fschindler commented on backend/migrations/default/1629358768576_alter_table_public_Program_add_column_VisiblityParticipationCertificate/up.sql
> +alter table "public"."Program" add column "VisiblityParticipationCertificate" boolean
I've fixed this.

2021-08-26 13:32 UTC, fschindler approved these changes
Finally all changes look good to me! I'm going to merge this.

2021-08-26 13:32 UTC, merged